# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4ce5edce78911f8bbd94ab1683bf74faaf5710d7226189b6e4e87fce75c5c022f8fb38bf28f0d7d4bdadc9ee484710556951ad1cc5e0aeb377121092a69e872

test:
  secret_key_base: 66989dc47a5203eaf938307a6617c1d507ebc97bdbb5dce31bafad3c2cbfb5f88073434b61e663504c42f57a10f19aa0afa1bb55af5b2207dd7deed26c14a5dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
